language: rust
rust:
  - stable
  - beta
install:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - cargo fmt -- --check
  - cargo clippy
  - cargo test --verbose
cache: cargo