#prompt = "{user} at {host} in {dir}\r\n$ "
[prompt]
user = {render = true, color = [206, 6, 123]}
caret = {render = true, on_newline = true }

[line]
capacity = 100

[colorize]
command = [0, 204, 0]