#prompt = "{user} at {host} in {dir}\r\n$ "
[prompt]
user = {render = true, color = {red = 206, green = 6, blue = 123}}
caret = {render = true, on_newline = true }

[line]
capacity = 100

[colorize]
command = {red = 0, green = 204, blue = 0}